### ISSUE TITLE
AttributeError message when running commands from commands.txt

### ISSUE THREAD

**Issue by alucic2** [AIFARMS/multi-camera-pig-tracking#9]
3840 1080
Process CameraManager-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/multi-camera-pig-tracking/manager.py", line 79, in run
    self.match_tracks_from_buffer()
  File "/Users/multi-camera-pig-tracking/manager.py", line 93, in match_tracks_from_buffer
    global_position_dict = self.match_tracks(self.ceiling_filter(self.local_buffer['ceiling'].pop(fid, None)),
  File "/Users/multi-camera-pig-tracking/manager.py", line 152, in match_tracks
    self.union_find.reset(ceil_id, min_id)
AttributeError: 'DisjointSet' object has no attribute 'reset'

**Comment by xttlcs** [comment]
Have you solved this problem?

**Comment by xttlcs** [comment]
i met the same problem,have you solved it? sincerely hoping for your request!!!

**Comment by 2333-Del** [comment]
> i met the same problem,have you solved it? sincerely hoping for your request!!!

Now I also encountered this problem, may I ask if you have solved it? If so, please be sure to reply to me. I look forward to your reply
